name: Update Pinned Nix Secrets Revision

on:
  workflow_dispatch:

jobs:
  sync:
    name: update
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.NIX_PAT }}

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Flake update
        run: nix flake update nix-secrets

      - name: Commit update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Run `nix flake update nixvim`" && git push || echo "No changes to commit"
