name: Nixvim

on:
  workflow_dispatch:

jobs:
  sync:
    name: update
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NIXVIM_UPDATE_TOKEN }}

      - name: Flake update
        run: nix flake update nixvim

      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
