name: Nixvim

on:
  workflow_dispatch:

jobs:
  sync:
    name: update
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        with:
          uses: actions/checkout@v4
          token: ${{ secrets.NIXVIM_UPDATE_TOKEN }}

      - name: Flake update
        uses: cachix/install-nix-action@v25
        run: nix flake update nixvim

      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Updated pinned commit in nixvim flake" && git push || echo "No changes to commit"
